### ISSUE TITLE
Multi-Arch Support (Feature Tracking Issues) 

### ISSUE THREAD

**Issue by dave-tucker** [bpfman/bpfman#1063]
eBPF bytecode can be compiled to bpfel or bpfeb depending on the target platform.

We should:

- Package both el/eb variants of BPF bytecode in an eBPF OCI image
- Ensure that bpfman is unpacking the correct artifact based on the runtime endianess
- It would be great if this worked the same way as multi-arch manifests (i.e we have a meta manifest that points to the actual image manifests for the correct os/arch)

This needs to be done for all the dispatcher images that we maintain + tooling created for user images to do this right.

Decide the list of arch'es we at least need

- arm64
- powerpc
- s390
- amd64 (x86) 
- Possibly more 

Since that's what's supported in https://github.com/netobserv/netobserv-ebpf-agent/tree/main/pkg/ebpf 

- [x] #1090
        - Package both el/eb variants of BPF bytecode in an eBPF OCI image
        - Determine if there's any existing OCI specific infrastructure that can help us here
        - It would be great if this worked the same way as multi-arch manifests (i.e we have a meta manifest that points to the actual image manifests for the correct os/arch)
- [x] #1091
- [x] #1092
- [x] #1093

**Comment by astoycos** [comment]
TODO expand into more issues :)

**Comment by astoycos** [comment]
Decide the list of arch'es we at least need

- arm64
- powerpc
- s390
- amd64 (x86) 

Since that's what's supported in https://github.com/netobserv/netobserv-ebpf-agent/tree/main/pkg/ebpf and 

- [ ] Update the OCI image spec used for packaging ebpf bytecode
        - Package both el/eb variants of BPF bytecode in an eBPF OCI image
        - Determine if there's any existing OCI specific infrastructure that can help us here
        - It would be great if this worked the same way as multi-arch manifests (i.e we have a meta manifest that points to the actual image manifests for the correct os/arch)
- [ ] Ensure that bpfman is unpacking the correct eBPF artifact based on the runtime endianess
- [ ] Build + pacakge all userspace libraries and binaries with multi arch support
- [ ] Build all eBPF bytecode images with multi arch support

**Comment by Billy99** [comment]
Feature Complete
