### ISSUE TITLE
Multi-Arch Support Master Issue

### ISSUE THREAD

**Issue by astoycos** [bpfman/bpfman#1088]
- [ ] Package both el/eb variants of BPF bytecode in an eBPF OCI image
- [ ] Ensure that bpfman is unpacking the correct artifact based on the runtime endianess
- [ ] It would be great if this worked the same way as multi-arch manifests (i.e we have a meta manifest that points to the actual
